### ISSUE TITLE
Workaround for problems with latest google maps version and zooming and centering. Not proper fix

### ISSUE THREAD

**Issue by andrewvanbreda** [Indicia-Team/client_helpers#11]
It seems the latest version of google maps has caused a breakage between it and Openlayers where if you use 'zoomToExtent' in the code, then the user cannot zoom in and out properly as the boundary is redrawn for the zoom, but the original boundary is also drawn. This used to be ok.

We have seen this behaviour with NPMS sites when using the "zoom_id" functionality in dynamic location to initially zoom the map to a boundary ghost location given as an id in the URL.

To get round this issue I have had to avoid using zoomToExtent, and centered the map on the boundary using setCenter. Then I used the options supplied to the map control in the form structure to supply the intial_zoom option.
Note that you could center the map on the boundary, and then use zoomTo in code, but this seems to zoom non-centrally to the boundary. 
The alternative it to zoom, then set the center, but doing this seems to cause the original issue.

As replacing zoomToExtent with setCenter and then supplying a configuration option is only a workaround (albeit an effective one), I have only committed the fix to the NPMS bitbucket code (commented out old code with a note to explain), not the general GitHub code. Maybe the zoomToExtent will start working again with further updates to openlayers and google maps.

**Comment by johnvanbreda** [comment]
I'm not currently able to reproduce this on iRecord. When viewing Explore My Records having selected a vice county in my account preferences, the map calls zoomToExtent to zoom to the county boundary. There are no obvious ill efects - I can zoom in and out and the boundary moves correctly. It's the same on other iRecord pages - no apparent problem. 
I presume you have the latest Openlayers.js files from the repository, as well as the latest helper_base file (which references the correct version of the api)?

**Comment by andrewvanbreda** [comment]
Thanks for everyone's help with this. It seems the issue is fixed by using the latest Openlayers, I was confused as I thought at least some of the sites had the latest files.
