### ISSUE TITLE
Fatal error on new install 

### ISSUE THREAD

**Issue by aengusrooneygrafana** [Indicia-Team/client_helpers#111]
Hello, I have just installed the Indicia modules for Drupal following this page 
https://indicia-docs.readthedocs.io/en/latest/site-building/iform/installation.html#installing-the-indicia-modules-for-drupal 

When I try to run these steps: 
```Now, visit Configuration > Indicia integration > Indicia settings on the admin toolbar and set the following options:```

I get the following error message when clicking on 'Settings' 

```Fatal error: require_once(): Failed opening required 'modules/drupal-8-module-iform-4.0.0/client_helpers/helper_base.php' (include_path='/opt/drupal/vendor/pear/pear_exception:/opt/drupal/vendor/pear/console_getopt:/opt/drupal/vendor/pear/pear-core-minimal/src:/opt/drupal/vendor/pear/archive_tar:.:/usr/local/lib/php') in /opt/drupal/web/modules/drupal-8-module-iform-4.0.0/iform.module on line 1020``` 

![image](https://user-images.githubusercontent.com/54800912/90341881-7b801b80-dffb-11ea-98a4-e00d9b8f4e46.png)

I can not see in the code where this should be changed - is this a known issue?  

Thanks!

**Comment by BirenRathod** [comment]
@aengusrooneygrafana Your error suggests that you haven't created the iform & indicia_feature folders in the modules folder.

**Comment by johnvanbreda** [comment]
@aengusrooneygrafana 2 things:
* Your module folder should be called iform, not drupal-8-module-iform-4.0.0.
* It looks like you've either downloaded the wrong file, or not done a recursive clone in Git. Am I right in thinking that your client_helpers folder inside the module is empty?

**Comment by aengusrooneygrafana** [comment]
Ah I see - I was trying 'Option 1 - Direct file download' to upload/unpack the zip file, but most have done something wrong.. 
 I changed to use the 'Option 2 - Installation using Git' approach and it worked perfectly - thank you!
