### ISSUE TITLE
XML report engine conundrum 

### ISSUE THREAD

**Issue by burkmarr** [Indicia-Team/client_helpers#121]
@johnvanbreda @andrewvanbreda @JimBacon - can anyone help me understand what's going on here?

I'm using the client_helpers lib to invoke a PoMS report on the Warehouse from a module outside iForm. I want to get the current IndiciaUser's records and it all works except that it has become apparent that I am only getting the user's records for the current year. I can't understand where that filter is coming from.

You can get a feel for how I'm calling the report from these PHP extracts:
```
$opts=array(
  'mode' => 'report',
  'dataSource' => trim($report['value']),
  'readAuth' => $read_auth,
  'sharing' => 'me',
  'userId' => $indiciaUserId,
);
report_helper::request_report($response, $opts, $currentParamValues, false);
```
The report SQL looks like this:
```
<query>
  select csn.id as sample,
  cttl.taxon as taxon,
  csn.attrs_json -&gt;&gt; '1050' as flower,
  coalesce((con.attrs_json -&gt;&gt; '666')::int, 0) as pomscount
  from cache_occurrences_functional o
  join cache_occurrences_nonfunctional con on con.id = o.id
  right join cache_samples_nonfunctional csn on o.sample_id = csn.id
  join cache_samples_functional s on s.id = csn.id
  join cache_taxa_taxon_lists cttl on cttl.id = o.taxa_taxon_list_id
  join websites w on w.id=o.website_id
  #agreements_join#
  WHERE #sharing_filter# 
  and o.survey_id in (636, 641, 637)
  and cttl.taxon_group LIKE 'Pollinator%'
  and extract(month from o.date_end) &gt; 3
  and extract(month from o.date_end) &lt; 10
  and array[214127, 1612, 1606, 1605, 1614] &amp;&amp; s.location_ids = true
</query>
```
There's no filter on year in the SQL, so I'm wondering if it's something to do with the implementation of `#agreements_join#` and `#sharing_filter#` but I've looked at the ReportEngine code and I can't see how that would be either. 

Does anyone have any insights?

**Comment by BirenRathod** [comment]
@burkmarr One of the thing notice on PoMS website that you have been using much older code of client_helpers module. could you update first that. this could be problem of communicating code from the warehouse. it may be calling old service which might not be in use any longer.

**Comment by johnvanbreda** [comment]
@burkmarr I don't think the age of the client_helpers library version you are using would cause a year filter to be applied. What report are you using and, if it's OK to share it, what is the user ID?

**Comment by johnvanbreda** [comment]
@burkmarr I've just spotted that the 3 survey datasets you are filtering on were only created in 2021, so therefore you will only be seeing data for this year as there can't be any earlier records.

**Comment by burkmarr** [comment]
omg!! Thanks @johnvanbreda. I was just finding the indicia user ID for you, but looks like I won't need that now! Thanks Jon - I've investigate what survey datasets are missing from my query.

**Comment by burkmarr** [comment]
@johnvanbreda - on closer inspection, that wasn't the problem  - I counted the records from those surveys and get plenty of older records (perhaps loaded retrospectively?). 
```
select extract(year from cof.date_start) as year, count(*)
from cache_occurrences_functional cof
where cof.survey_id in (636, 641, 637)
group by year
order by year
```
![image](https://user-images.githubusercontent.com/9275178/126151217-d80763d8-daaf-4cd7-83cd-acd6953ee892.png)

So I went looking for the Indicia User ID for the user where this was noticed (Claire Carvel) and found something surprising - her records have two different created_by_id's in cache_occurrences_functional - 82207 and 301649. The former user is flagged as deleted and the new one accounts for all the 2021 records. However *all* the records are linked to samples with a created_by_id of 301649. So filtering on created by id in samples gets all the records, but filtering on created by id in occurrences gets only this years. Is this a data problem that needs fixing or can I change my report to sort it out?

**Comment by DavidRoy** [comment]
tagging @andrewvanbreda and @johnvanbreda as there were some issues with accounts getting deleted. This affected Claire. I'm not sure if we've goto the bottom of this yet

**Comment by johnvanbreda** [comment]
@DavidRoy I'll pick this up as I've been looking at the account deletion issue.

**Comment by johnvanbreda** [comment]
This particular case probably relates to an old bug regarding case sensitivity and email addresses. Claire did have 3 accounts in total but 2 are deleted and 1 still had records attached. I've cleaned this up so all the records are attached to one account. I've also checked her BeeWalk and iRecord accounts are correctly linked to this account but I've not done it for PoMS as I don't think I have the admin login.

@andrewvanbreda here is what you need to do. 
1. On PoMS, go to admin/config/people/accounts/form-display then move Indicia Warehouse User ID from the Disabled section into the form.
2. Find Claire's account, then edit it.
3. Delete the Indicia Warehouse User ID field value (should be 82207).
4. Save the account and it will re-link, the value should now be 301649.
5. Remove Indicia Warehouse User ID from the form.

**Comment by burkmarr** [comment]
I think Claire's ID is probably already set to 301649 - because that was the ID that linked to the 2021 records which my report was pulling back?

**Comment by burkmarr** [comment]
My report does seem to be getting all the records now - thanks @johnvanbreda

**Comment by burkmarr** [comment]
(All Claire's records I mean.)

**Comment by johnvanbreda** [comment]
According to the users_websites table, 306132 is linked to websites 48, 23 and 134, but 82361 was linked to 136 and 48. So website 136 still needs the warehouse user ID updating in the user profile.

**Comment by andrewvanbreda** [comment]
@johnvanbreda @burkmarr 
This had already been done when I initially noticed the problem with Claire's account being attached to deleted record, but I have deleted it again and it did relink back onto 301649

**Comment by johnvanbreda** [comment]
Can this be closed @burkmarr ?
