### ISSUE TITLE
Termlist icons don't display (at least not on PoMS Drupal 8)

### ISSUE THREAD

**Issue by andrewvanbreda** [Indicia-Team/client_helpers#122]
Raising this as a general Indicia note, as I tried to get this to work on the PoMS project, but it is not considered essential for the project so I have no further budget to work on it.

Page
https://ukpoms.org.uk/enter-fit-count

Attribute on page
How much of your 50x50cm patch was occupied by the target flowers?

Sample attribute 1052 in BRC Live Warehouse

Termlist 669

The icons from this termlist don't seem to appear on the website.

**Comment by johnvanbreda** [comment]
Did you include @termImageSize=thumb or similar in the config for this control?

**Comment by andrewvanbreda** [comment]
@johnvanbreda 
Thanks, I had tried many things but actually this one is working.
Interestingly this wasn't necessary on iRecord
