### ISSUE TITLE
Common names not displaying on species grid

### ISSUE THREAD

**Issue by andrewvanbreda** [Indicia-Team/client_helpers#63]
When we upgraded the NPMS training site to the latest development branch I noticed the common names on our preloaded species grids were not displaying. It was displaying a token {common} instead. This appears to occur on master also
This is actually an npms_sample_occurrence form that extends dynamic_sample_occurrence

I noticed that on a normal dynamic_sample_occurrence that the common name wasn't displaying at all (not even a tag) with exactly the same form settings.

I think the issue started to appear because of the data_entry_helper changes here

https://github.com/Indicia-Team/client_helpers/commit/4cbb8359d852d9e428114cd1d0fe49a28af49854#diff-776c9b7328c594476e240f1ec163748d

Note that refreshing the screen does not appear to be enough, I seem to need to close and re-open the browser to get the problem to appear/reappear

The behaviour with just an extra species list (not preloaded) appears to be different yet again. When the problem is occurring with the {common} tag on npms_sample_occurrence switching to extra species results in no common name at all

As a last ditch test, I just tried master branch, normal dynamic_sample_occurrence. Both Species and Extra Species list selected, "Include both names in species controls and added rows" select and a species list filter, and the common name still wasn't visible (and yes the species does have a common name)

**Comment by johnvanbreda** [comment]
@andrewvanbreda Does the NPMS code do anything special with the way it loads the species list? I.e. does it override the template or the table the species are loaded from?
If not, please email me a link which shows the error and login info if needed.

**Comment by JimBacon** [comment]
I note in the diff Andy linked to that the token was changed from {common} to {default_common_name}.

**Comment by andrewvanbreda** [comment]
@johnvanbreda @JimBacon Yes it does, it builds a taxon label with build_grid_taxon_label_function. 
I can see it using {common}. I did just try changing the token to {default_common_name} in the function and the common name doesn't appear at all now.
This is now inline with the standard dynamic_sample_occurrence behaviour I am seeing.
So why can't I see the common name at all is the question

The taxon label code for NPMS is as follows (with the original token)

  protected static function build_grid_taxon_label_function($args, $options) {
    global $indicia_templates;
    // This bit optionally adds '- common' or '- latin' depending on what was being searched
    if (isset($args['species_include_both_names']) && $args['species_include_both_names']) {
      $php = '$r = "<span class=\"scTaxon\"><em>{taxon}</em></span> <span class=\"scCommon\">{common}</span>";' . "\n";
    } else {
      $php = '$r = "<em>{taxon}</em>";' . "\n";
    }
    // this bit optionally adds the taxon group
    if (isset($args['species_include_taxon_group']) && $args['species_include_taxon_group']) {
      $php .= '$r .= "<br/><strong>{taxon_group}</strong>";' . "\n";
    }
    if (isset($options['useCommonName'])&&$options['useCommonName']==true) 
      $php = '$r = "<span class=\"scCommon\">{common}</span>";' . "\n";
    // Close the function
    $php .= 'return $r;' . "\n";
    // Set it into the indicia templates
    $indicia_templates['taxon_label'] = $php;
  }

**Comment by johnvanbreda** [comment]
@andrewvanbreda I have a development dynamic sample occurrence form running on my laptop, with either master or develop branch (which currently are virtually identical) and I am seeing the common names OK. I presume you have the "Include both names" option set?

Have you tried debugging the content of your taxon label template? You could also look at the value in $firstColumnTaxon at the point the PHP is evaluated (data entry helper around line 3369).

**Comment by andrewvanbreda** [comment]
@johnvanbreda You say to debug it, but it used to be absolutely fine.
BRC are also getting the issue on their NPMS training site.
Anyway, I will see if I can change NPMS to work with the altered data_entry_helper. I will get back to you.

**Comment by andrewvanbreda** [comment]
@johnvanbreda 
The problem is that there is a get_population_date in the get_species_checklist_taxa_list function that is no longer returning a "common" field for its records.
It seems the table parameter being passed to the get_population_date has been changed to "taxa_search" when it used to be "taxa_taxon_list"
Manually changing this options actually fixes my issue.
Now the question is should this "taxa_search" be returning a field called "common". It seems to return "default_common_name" which does contain the common name.

I tried changing the {common} tag in my taxon label code to default_common_name and this time it seemed to work after persisting with closing the browser, clearing caches, it seems to be really difficult to get changes to filter down to the page.

Is this an official fix though? My normal dynamic_sample_occurrence is now working, so that might of been the issue that I am struggling to get changes to filter down to the page.

So my question is should I just change the tag, or should get_population_data for taxa_search be returning a field called "common" like the old get_population_data for taxa_taxon_list used to?

**Comment by johnvanbreda** [comment]
@andrewvanbreda Prior to the commit referenced at the top of this thread, there were several different methods of loading species lists and lots of switching code which adapted the templates depending on the load method. For example in some cases the field for common names was called default_common_name, in others it needed to switch to common_name. This commit was inteded to ensure all taxon name loading for lists comes from a consistent source (taxa_search - see http://indicia-docs.readthedocs.io/en/latest/developing/web-services/data-services-taxon-search.html). So it is indeed correct that you should change the field name in your templates to default_common_name.

I did send an email round as this was going to be a breaking change back in August - unfortunately it was not going to be possible to tidy the code up to this extent without introducing a breaking change.

**Comment by andrewvanbreda** [comment]
@johnvanbreda OK, I will close this then as I have an NPMS issue related to it.
I remember the email now, but it was sent at a time when I didn't realise it would impact NPMS as had forgotten we had any custom built taxon labels (as they were done ages ago)
