### ISSUE TITLE
Edit Taxon page has problems when using synonyms

### ISSUE THREAD

**Issue by andrewvanbreda** [Indicia-Team/client_helpers#84]
The new Edit Taxon (dynamic taxon) non-warehouse page for websites has an issue with synonyms.
Currently it can be loaded with a synonym, however saving seems to auto-switch this to be the preferred species without informing the user.
This page probably shouldn't allow editing of synonyms apart from in the synonyms box for preferred species.
Perhaps load the preferred species if a synonym load is attempted?

**Comment by johnvanbreda** [comment]
Deployed to DGfM warehouse.
