### ISSUE TITLE
Hierarchical drop-down doesn't load for Safari browser

### ISSUE THREAD

**Issue by andrewvanbreda** [Indicia-Team/client_helpers#85]
Using Master branches for everything. Using a Drupal-8 site.
Safari 12.0.2
Hierarchical drop-downs do not load their date when loading a data entry page.
Going to identical address in Firefox works perfectly.
Seems to be fine for non-hierarchical.

This has implications as it would mean further saves made by user may result in data loss.

**Comment by johnvanbreda** [comment]
@andrewvanbreda I can't reproduce this on iRecord using Safari. Are there any JavaScript errors?

**Comment by andrewvanbreda** [comment]
Only the usual warning
Google Maps JavaScript API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys

I don't think this is it. I have seen this on Eric though, try the Habitat drop-down on this. I will let Paul there know I entered this test record and will delete it when done.

http://www.ericnortheast.org.uk/wildlife/record/single?occurrence_id=184863

**Comment by andrewvanbreda** [comment]
@johnvanbreda Not sure if you got a mail about my reply above

**Comment by johnvanbreda** [comment]
@andrewvanbreda can this be closed?

**Comment by andrewvanbreda** [comment]
Will close.
Seems to work on new Safari anyway.
